### ISSUE TITLE
FYI: Scoring file changes

### ISSUE THREAD

**Issue by smlmbrt** [maialab/quincunx#1]
Hi @ramiromagno, just a heads up that we plan to change the headers of the scoring files on December 15, 2021, and rename one of the columns from _reference_allele_ to _other_allele_. I'd imagine this would only impact the scoring file reading part: https://github.com/maialab/quincunx/blob/a5850ed3f7b9b918974bd2f9e3bf5b1bcd42a8ba/R/read_pgs_scoring_file.R but it also involves the weight_type column being integrated as score metadata. You can read more about the changes here: https://www.pgscatalog.org/news/

**Comment by ramiromagno** [comment]
Hi @smlmbrt, thank you for letting me know!

Could you share a small example file that includes those changes for me to test?

**Comment by smlmbrt** [comment]
We updated the notice to have an example file linked at the top. But here is the link: https://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000001/ScoringFiles/format_v2/PGS000001.txt.gz
